spring:
  application:
    name: TASK-SERVICE # Correct placement for the application name
  datasource:
    url: jdbc:mysql://localhost:3306/task_service
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9092

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Uncomment and set the active profile as needed
#spring.profiles.active: ${ENV:dev}
